### ISSUE TITLE
chore(opt8n): Add Example's Crate with Foundry Scripts 

### ISSUE THREAD

**Issue by 0xOsiris** [ethereum-optimism/op-test-vectors#35]
I think it'd be useful to have a simple runnable foundry script in the repository both for workflow/testing, and for streamling DevX for anyone using opt8n. 

Some people may not be familiar with foundry scripts as well, so it can serve as nice template to build from.
 
Thinking just a `examples/foundry-scripts` crate with a foundry workspace (maybe couple different scripts), and a binary to automate generating the execution fixtures.

**Comment by refcell** [comment]
Strong agree - thanks for putting this up, great issue

**Comment by refcell** [comment]
Completed today ✅
